### ISSUE TITLE
Set up Docker

### ISSUE THREAD

**Issue by anorthall** [anorthall/caves.app#1]
- [x] Set up docker-compose
- [x] Create development environment
- [x] Add auto-installation of test database
- [x] Create production environment
