### ISSUE TITLE
Create integration tests for major flows

### ISSUE THREAD

**Issue by anorthall** [anorthall/caves.app#44]
Integration tests should be created for:

- [x] User registration
- [x] Logging in
- [x] Creating a trip
- [x] Editing a trip
- [x] Deleting a trip
- [x] Listing trips
- [x] Viewing the home page
- [x] Viewing the unregistered users page
- [x] Viewing the about page
- [x] Viewing the statistics page
- [x] Viewing the user profile
- [x] Changing email
- [x] Changing password
- [x] Changing the user profile
- [x] Resending email verification
- [x] Resetting password 
- [x] Exporting to CSV
