### ISSUE TITLE
Clean up project configuration files

### ISSUE THREAD

**Issue by anorthall** [anorthall/caves.app#63]
The Django settings directory (currently `app/cavinglog`) should be moved to the project root - `config/django`.

The new `config/` directory should contain both the Django configuration files, and the Docker configuration files currently contained within `etc/`. These should be placed in `config/docker/development` and `config/docker/production`, respectively.

Separate Django configuration files should be created for development and production, inheriting from a base configuration file. Separate requirements.txt files should be created for development and production. Development only packages, such as django-debug-toolbar, should not be loaded in production, nor installed.

### Tasks
- [x] Move Django settings directory to `$ROOT/config/django`
- [x] Move Docker configuration to `$ROOT/config/docker`
- [x] Create separate `requirements.txt` files for development and production
- [x] Create separate Django configuration files for development and production
