### ISSUE TITLE
Make the repository public and open source the project

### ISSUE THREAD

**Issue by anorthall** [anorthall/caves.app#73]
The following tasks need to be completed before the repository is made public:

- [x] An improved README.md
- [x] A very brief contributions guide in the README
- [x] Updated test data for the development instance
- [x] Double checking of all env files, Dockerfiles, configuration files for any sensitive information
- [x] Allow 'one command' running of the development instance - no copying of configuration files, etc.
- [x] Make a final decision on project licensing
